# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Person": "00_person.ipynb"}

modules = ["person.py"]

doc_url = "https://tktran11.github.io/nbdev_try/"

git_url = "https://github.com/tktran11/nbdev_try/tree/master/"

def custom_doc_links(name): return None
